# Generated by Django 4.1.1 on 2022-09-19 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='question_survey',
            field=models.CharField(default='default Value', max_length=200),
            preserve_default=False,
        ),
    ]
